# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aafc21b37a8e5a34cf7bf97e0e364e39867bd27778833314c6c011daa7e00e44647a5693d6ec4a1993795f56498d1e4e3a40bc61d2a7ff0233336e6624c5b0a4

test:
  secret_key_base: b50c2e5458750d441720bd6f15c5a78b48cb1cc4de924fe232c7d02a24e49365bd78a7a73bfcd5c607f39001853c96429712ebe5fce6c4a1fe3fc1f502faa06a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
